export const FETCH_POINTS_REQUEST = "FETCH_POINTS_REQUEST";
export const FETCH_POINTS_SUCCESS = "FETCH_POINTS_SUCCESS";
export const FETCH_POINTS_ERROR = "FETCH_POINTS_ERROR";
export const SELECTED_ADDRESS_POINT = "SELECTED_ADDRESS_POINT";
