export const CHOOSE_COLOR_CAR = "CHOOSE_COLOR_CAR";
export const CHOOSE_RENTAL_PERIOD_CAR = "CHOOSE_RENTAL_PERIOD_CAR";
export const CHOOSE_TIMES_RENT_CAR = "CHOOSE_TIMES_RENT_CAR";
export const CHOOSE_RATE_CAR = "CHOOSE_RATE_CAR";
export const CHOOSE_FULL_TANK_CAR = "CHOOSE_FULL_TANK_CAR";
export const CHOOSE_CHILD_SEAT_CAR = "CHOOSE_CHILD_SEAT_CAR";
export const CHOOSE_RIGHT_HAND_DRIVE_CAR = "CHOOSE_RIGHT_HAND_DRIVE_CAR";
