export const FETCH_MODELS_REQUEST = "FETCH_MODELS_REQUEST";
export const FETCH_MODELS_SUCCESS = "FETCH_MODELS_SUCCESS";
export const FETCH_MODELS_ERROR = "FETCH_MODELS_ERROR";
export const GET_FILTER_NAME = "GET_FILTER_NAME";
export const CHOOSE_MODEL_CAR = "CHOOSE_MODEL_CAR";
